version: '3'
services:
  product-service:
    build: .
    ports:
      - "8000:8000"
    networks:
      - app-network

  order-service:
    build: .
    ports:
      - "9000:9000"
    networks:
      - app-network

networks:
  app-network:
