name: CD Pipeline

on:
 workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
  
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: pannathatdev
            password: dckr_pat_RUMz0NKUUwMZzFEElvaufKdNQ3g
  
        - name: Build and push Docker image
          run: |
            docker build -t pannathatdev/product:latest .
            docker push pannathatdev/product:latest
          working-directory: ./product-service
  
        - name: Deploy to production
          env:
            MONGO_URI: mongodb+srv://pipo:Aa123654@pipo.gqdqli4.mongodb.net/product
          run: |
            echo "Deploying to production..."
            docker run -d -p 8000:8000 -e MONGO_URI=$MONGO_URI pannathatdev/product:latest
