name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
    env:
      MONGO_URI: mongodb+srv://pipo:Aa123654@pipo.gqdqli4.mongodb.net/product

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./product-service

      - name: Run unit tests
        run: npm run test:unit
        working-directory: ./product-service

      - name: Load Mockup Data
        run: node src/product/mockup-loader.js
        working-directory: ./product-service

      - name: Build the Docker image
        run: docker build -t product-service:latest .
        working-directory: ./product-service

      - name: Save Docker image to a file
        run: docker save product-service:latest -o product-service.tar
        working-directory: ./product-service

      - name: Upload Docker image to GitHub Actions
        uses: actions/upload-artifact@v2
        with:
          name: product-service-image
          path: ./product-service/product-service.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Docker image from GitHub Actions
        uses: actions/download-artifact@v2
        with:
          name: product-service-image
          path: ./product-service

      - name: Load Docker image
        run: docker load -i ./product-service/product-service.tar

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Tag image
        run: docker tag product-service:latest ghcr.io/${{ secrets.GHCR_USERNAME }}/product-service:latest

      - name: Push to GitHub Container Registry
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/product-service:latest
