name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout product-service repository
        uses: actions/checkout@v2
        with:
          repository: pannathatdev/product-service
          path: product-service

      - name: Checkout order-service repository
        uses: actions/checkout@v2
        with:
          repository: pannathatdev/order-service
          path: order-service

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies for product-service
        run: npm install
        working-directory: ./product-service/product-service

      - name: Install dependencies for order-service
        run: npm install
        working-directory: ./order-service/order-service

      - name: Install MongoDB Tools
        run: apt-get install -y mongodb-clients

      - name: Import Mock Data into MongoDB Atlas
        env:
          MONGO_URI: mongodb+srv://pipo:Aa123654@pipo.gqdqli4.mongodb.net/product
        run: |
          mongoimport --uri "$MONGO_URI" --collection products --file ./mock-products.json --jsonArray
          
      - name: Run unit tests for product-service
        run: npm run test:unit
        working-directory: ./product-service/product-service

      - name: Run unit tests for order-service
        run: npm run test:unit
        working-directory: ./order-service/order-service

      - name: Build the Docker image for product-service
        run: docker build -t product .
        working-directory: ./product-service/product-service

      - name: Build the Docker image for order-service
        run: docker build -t order .
        working-directory: ./order-service/order-service

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout product-service repository
        uses: actions/checkout@v2
        with:
          repository: pannathatdev/product-service
          path: product-service

      - name: Checkout order-service repository
        uses: actions/checkout@v2
        with:
          repository: pannathatdev/order-service
          path: order-service

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: pannathatdev
          password: dckr_pat_RUMz0NKUUwMZzFEElvaufKdNQ3g

      - name: Build and push Docker image for product-service
        run: |
          docker build -t pannathatdev/product:latest .
          docker push pannathatdev/product:latest
        working-directory: ./product-service

      - name: Build and push Docker image for order-service
        run: |
          docker build -t pannathatdev/order:latest .
          docker push pannathatdev/order:latest
        working-directory: ./order-service

      - name: Deploy to production
        env:
          MONGO_URI: mongodb+srv://pipo:Aa123654@pipo.gqdqli4.mongodb.net/product
        run: |
          echo "Deploying to production..."
          docker run -d -p 8000:8000 -e MONGO_URI=$MONGO_URI pannathatdev/product:latest
          docker run -d -p 8001:8000 -e MONGO_URI=$MONGO_URI pannathatdev/order:latest
