name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
    env:
      MONGO_URI: mongodb+srv://pipo:Aa123654@pipo.gqdqli4.mongodb.net/product

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./product-service

      - name: Run unit tests
        run: npm run test:unit
        working-directory: ./product-service

      - name: Load Mockup Data
        run: node mockup-loader.js
        working-directory: ./product-service

      - name: Build the Docker image
        run: docker build -t product .
        working-directory: ./product-service

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: pannathatdev
          password: dckr_pat_RUMz0NKUUwMZzFEElvaufKdNQ3g

      - name: Build and push Docker image
        run: |
          docker build -t pannathatdev/product:latest .
          docker push pannathatdev/product:latest
        working-directory: ./product-service

      - name: Deploy to production
        env:
          MONGO_URI: mongodb+srv://pipo:Aa123654@pipo.gqdqli4.mongodb.net/product
        run: |
          echo "Deploying to production..."
          docker run -d -p 8000:8000 -e MONGO_URI=$MONGO_URI pannathatdev/product:latest
