name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    env:
      MONGO_URI: mongodb://localhost:27017/nest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./product-service

      - name: Build the Docker image
        run: docker build -t product .
        working-directory: ./product-service

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: pannathatdev
          password: Aa123654

      - name: Push the Docker image
        run: docker push product:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to production
        env:
          MONGO_URI: mongodb+srv://pipo:Aa123654@pipo.gqdqli4.mongodb.net/product
        run: |
          echo "Deploying to production..."
          docker run -d -p 8000:3000 -e MONGO_URI=$MONGO_URI product:latest
